---
title: "day_7_activity"
author: "Jake Eisaguirre"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(here)
```

```{r}
bird_observations <- read_csv(here("data", "knb-lter-cap.256.9", "52_pp52_birds_1.csv"))

sites <- read_csv(here("data", "knb-lter-cap.256.9","52_pp52_sites_1.csv"))

surveys <- read_csv(here("data", "knb-lter-cap.256.9","52_pp52_surveys_1.csv"))

taxalist <- read_csv(here("data", "knb-lter-cap.256.9","52_pp52_taxalist_1.csv"))
                 


bird_subset <- bird_observations %>% 
  
  filter(species_id %in% c("BHCO", "RWBL")) %>% 
  
  filter(site_id %in% c("LI-W", "NU-C"))


```

```{r}

bird_left_1 <- left_join(bird_subset, taxalist, by = "species_id") 

bird_left <- left_join(bird_left_1, sites, by = "site_id")
  
 

```

```{r}

birds_full <- full_join(bird_subset, sites, by = "site_id")

```

```{r}

birds_inner <- inner_join(bird_subset, taxalist, by = "species_id")

left_birds_join <- left_join(bird_subset, taxalist, by = "species_id")


```


```{r}

bird_observations <- bird_observations %>% 
  rename(bird_obs_notes = notes)

bird_1 <- full_join(bird_observations, taxalist, by = "species_id")

bird_2 <- full_join(bird_1, sites, by = "site_id")

final_bird <- full_join(bird_2, surveys, by = c("site_id", "survey_id"))


big_bird <- final_bird %>% 
  select(survey_date, common_name, park_name, bird_count)

new_big_bird <- big_bird %>% 
  mutate(survey_month = month(survey_date)) %>% 
  mutate(survey_month = as.factor(survey_month)) %>% 
  relocate(survey_month, .after = survey_date)

tot_birds <- new_big_bird %>% 
  group_by(park_name, survey_month) %>% 
  summarize(count = (tot_birds = n())) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))

  

```

```{r}



```

